name: 참외로운개발
title: LeeWS

# 사진넣는곳
# lightavatar: /assets/images/light_bauhaus_logo.png
# darkavatar: /assets/images/dark_bauhaus_logo.png

tagline: tagline

# A longer description used for the description meta tag. Also used as fallback for pages that don't provide their own description, and also as part of the page's title tag if neither page.title nor site.tagline has been defined.
description: 
url: ws0819.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

# global author information
author: andrew-park

# URL to a site-wide logo (e.g., /assets/your-company-logo.png)
logo: /assets/images/light_bauhaus_logo.png

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

permalink: /:year/:month/:day/:title/

# Includes an icon in the footer for each username you enter
footer-links:
  email: seob0819@gmail.com
  # facebook:
  github: 
  # instagram: andrewhwanpark
  # linkedin: andrewhwanpark
  # rss: # just type anything here for a working RSS icon
  # twitter: andrewhwanpark

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
